### ISSUE TITLE
Last weekend of month recurring isssue

### ISSUE THREAD

**Issue by RedditPilot** [shanet/pirep#164]
When adding an event on a 4th Saturday of this month as a recurring event, the only options available are 

every (date) of the month 
Last Saturday of the month.  

In this case (November) the 4th Saturday is the last Saturday of the month but that isn’t always going to be the case.  Some months can have 5 Saturdays which would place this event on the wrong weekend.   

There needs to be a way to add 
Every [1st,2nd..5th] [Sunday, Monday…Saturday] of the month.   

Some places only host events when there is a 5th Saturday.   And some places host events on the 4th Saturday which isn’t always going to be the last Saturday.   

 Very nice to see the events addition!

**Comment by shanet** [comment]
Heh, I wrote in a comment about how I was hoping to simplify the logic and not need to handle this case: https://github.com/shanet/pirep/blob/master/app/assets/javascripts/airports/events.js#L148.

Guess that didn't last long. :) I'll try to separate out the "last" day of the month into a "fourth" and "last" option.

**Comment by shanet** [comment]
Actually this wasn't too difficult to add. Now when the start date is on the 4th or 5th week of the month the recurring week-of-month drop down will display two options: one for the 4th/5th week and one for the last week.
