### ISSUE TITLE
Open in Foreflight Button

### ISSUE THREAD

**Issue by RedditPilot** [shanet/pirep#95]
Would love an "Open in Foreflight" or comparable apps button.   Especially for some of the unlisted or uncharted locations, an easy one import into foreflight would help bridge the gap between researching in PIREP.IO and adding the airport or location into foreflight to execute navigating to that location.  

SkyVector has this functionality to export a route to foreflight.  As does the mobile version of flightaware, where you can view a route and import it into foreflight.  

SkyVector offers export to:
ForeFlight
WingX
FlyQ
Garmin Pilot
Oz RWY
AvPlan EFB

**Comment by shanet** [comment]
That's cool, I wasn't aware that ForeFlight had support for URL schemes. There's now an "Open in Foreflight" link on airports when viewing the page on iOS. I also added a fuel prices link while I was at it.

PR #97
